/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPOS;
import DbConn.DbConn;
import java.awt.Font;
import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author IT-Laotelecom
 */
public class mainpos1 extends javax.swing.JFrame {
    
     Connection C=DbConn.getConn();
     DefaultTableModel Modelproduct;
     DefaultTableModel ModelPOS;
     DefaultTableModel ModelCatagory;
     DefaultTableModel ModelOrder;
     DefaultComboBoxModel Modelcombox;
    
    /**
     * Creates new form mainpos1
     */
    public mainpos1() {
         initComponents();
         product_table.getTableHeader().setFont(new Font("Phetsarath OT",Font.PLAIN,14){});
         catagory_table.getTableHeader().setFont(new Font("Phetsarath OT",Font.PLAIN,14){});
         pos_table.getTableHeader().setFont(new Font("Phetsarath OT",Font.PLAIN,14){});
         order_bill.getTableHeader().setFont(new Font("Phetsarath OT",Font.PLAIN,14){});
         Modelproduct=(DefaultTableModel)product_table.getModel();
         ModelPOS=(DefaultTableModel)pos_table.getModel();
         ModelCatagory=(DefaultTableModel)catagory_table.getModel();
         ModelOrder=(DefaultTableModel)order_bill.getModel();
         Modelcombox=(DefaultComboBoxModel)catagory_combo.getModel();
         
         price_field2.setEditable(false);
         product_field2.setEditable(false);
    }
    
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        icon_label = new javax.swing.JLabel();
        product_label = new javax.swing.JLabel();
        catagory_label = new javax.swing.JLabel();
        POS_label = new javax.swing.JLabel();
        bill_label = new javax.swing.JLabel();
        about_label = new javax.swing.JLabel();
        exit_label = new javax.swing.JLabel();
        top_panel = new javax.swing.JPanel();
        show_panel = new javax.swing.JPanel();
        product_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        barcode_field = new javax.swing.JTextField();
        product_field = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        balance_field = new javax.swing.JTextField();
        save_btn = new javax.swing.JButton();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        price_field = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        clear_btn2 = new javax.swing.JButton();
        catagory_combo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        product_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        catagory_panel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        catagory_table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        catagory_field2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        status_combobox = new javax.swing.JComboBox<>();
        save_btn1 = new javax.swing.JButton();
        update_btn1 = new javax.swing.JButton();
        delete_btn1 = new javax.swing.JButton();
        POS_panel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pos_table = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        barcode_field2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();
        pay_btn = new javax.swing.JButton();
        deletePOS_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        total_field2 = new javax.swing.JTextField();
        product_field2 = new javax.swing.JTextField();
        quantity_field2 = new javax.swing.JTextField();
        price_field2 = new javax.swing.JTextField();
        receive_field2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        change_field2 = new javax.swing.JTextField();
        clear_btn = new javax.swing.JButton();
        bill_panel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        order_bill = new javax.swing.JTable();
        deletebill_btn = new javax.swing.JButton();
        refreshbill_btn = new javax.swing.JButton();
        about_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menu_panel.setBackground(new java.awt.Color(244, 244, 244));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        icon_label.setForeground(new java.awt.Color(0, 102, 204));
        icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_label.setText("SM-POS");
        menu_panel.add(icon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 76));

        product_label.setBackground(new java.awt.Color(255, 255, 255));
        product_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        product_label.setForeground(new java.awt.Color(0, 0, 0));
        product_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        product_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box (1).png"))); // NOI18N
        product_label.setText("         ສິນຄ້າ");
        product_label.setToolTipText("");
        product_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        product_label.setOpaque(true);
        product_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                product_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                product_labelMouseExited(evt);
            }
        });
        menu_panel.add(product_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        catagory_label.setBackground(new java.awt.Color(255, 255, 255));
        catagory_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        catagory_label.setForeground(new java.awt.Color(51, 51, 51));
        catagory_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        catagory_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miscellaneous (1).png"))); // NOI18N
        catagory_label.setText("      ປະເພດສິນຄ້າ");
        catagory_label.setOpaque(true);
        catagory_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catagory_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catagory_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catagory_labelMouseExited(evt);
            }
        });
        menu_panel.add(catagory_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));

        POS_label.setBackground(new java.awt.Color(255, 255, 255));
        POS_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        POS_label.setForeground(new java.awt.Color(51, 51, 51));
        POS_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag (1).png"))); // NOI18N
        POS_label.setText("       ຂາຍສິນຄ້າ");
        POS_label.setOpaque(true);
        POS_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                POS_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                POS_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                POS_labelMouseExited(evt);
            }
        });
        menu_panel.add(POS_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, -1));

        bill_label.setBackground(new java.awt.Color(255, 255, 255));
        bill_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        bill_label.setForeground(new java.awt.Color(51, 51, 51));
        bill_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bill_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill (1).png"))); // NOI18N
        bill_label.setText("        ໃບບິນ");
        bill_label.setOpaque(true);
        bill_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bill_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bill_labelMouseExited(evt);
            }
        });
        menu_panel.add(bill_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, -1));

        about_label.setBackground(new java.awt.Color(255, 255, 255));
        about_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        about_label.setForeground(new java.awt.Color(51, 51, 51));
        about_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png"))); // NOI18N
        about_label.setText("        ກ່ຽວກັບ");
        about_label.setOpaque(true);
        about_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                about_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about_labelMouseExited(evt);
            }
        });
        menu_panel.add(about_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 35));

        exit_label.setBackground(new java.awt.Color(255, 255, 255));
        exit_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        exit_label.setForeground(new java.awt.Color(51, 51, 51));
        exit_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        exit_label.setText("     ອອກຈາກລະບົບ");
        exit_label.setOpaque(true);
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        menu_panel.add(exit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, -1));

        top_panel.setBackground(new java.awt.Color(51, 51, 51));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_panel.setLayout(new java.awt.CardLayout());

        product_panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        barcode_field.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        product_field.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel3.setText("ລະຫັດບາໂຄດ:");

        jLabel4.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel4.setText("ຊື່ສິນຄ້າ:");

        jLabel5.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel5.setText("ປະເພດສິນຄ້າ:");

        jLabel6.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel6.setText("ຈຳນວນສິນຄ້າ:");

        balance_field.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        save_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        save_btn.setText("ບັນທຶກ");
        save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btnActionPerformed(evt);
            }
        });

        update_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        update_btn.setText("ແກ້ໄຂ");
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });

        delete_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        delete_btn.setText("ລຶບ");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        price_field.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel16.setText("ລາຄາສິນຄ້າ:");

        clear_btn2.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        clear_btn2.setText("ລ້າງ");
        clear_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn2ActionPerformed(evt);
            }
        });

        catagory_combo.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(catagory_combo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(product_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(barcode_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(price_field, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(balance_field, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(109, 109, 109))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(save_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(update_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clear_btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(delete_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barcode_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(balance_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(product_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catagory_combo, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(price_field, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(save_btn)
                            .addComponent(update_btn)
                            .addComponent(clear_btn2)
                            .addComponent(delete_btn))
                        .addGap(16, 16, 16))))
        );

        product_table.setBackground(new java.awt.Color(255, 255, 255));
        product_table.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        product_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ສິນຄ້າ", "ບາໂຄດ", "ຊື່ສິນຄ້າ", "ລາຄາ", "ຈຳນວນ", "ປະເພດສິນຄ້າ"
            }
        ));
        product_table.setGridColor(new java.awt.Color(255, 255, 255));
        product_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(product_table);

        jLabel1.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ສິນຄ້າ");

        javax.swing.GroupLayout product_panelLayout = new javax.swing.GroupLayout(product_panel);
        product_panel.setLayout(product_panelLayout);
        product_panelLayout.setHorizontalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(412, 412, 412))
            .addGroup(product_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
        );
        product_panelLayout.setVerticalGroup(
            product_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(product_panelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        show_panel.add(product_panel, "card2");

        catagory_panel.setBackground(new java.awt.Color(255, 255, 255));

        catagory_table.setBackground(new java.awt.Color(255, 255, 255));
        catagory_table.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        catagory_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ລະຫັດ", "ຊື່", "ສະຖານະ"
            }
        ));
        catagory_table.setGridColor(new java.awt.Color(255, 255, 255));
        catagory_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catagory_tableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(catagory_table);

        jLabel2.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ປະເພດສິນຄ້າ");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        catagory_field2.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel7.setText("ປະເພດສິນຄ້າ:");

        jLabel8.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel8.setText("ສະຖານະ:");

        status_combobox.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        status_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ຍັງເຫລືອ", "ບໍ່ເຫລືອ" }));

        save_btn1.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        save_btn1.setText("ບັນທຶກ");
        save_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_btn1ActionPerformed(evt);
            }
        });

        update_btn1.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        update_btn1.setText("ແກ້ໄຂ");
        update_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btn1ActionPerformed(evt);
            }
        });

        delete_btn1.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        delete_btn1.setText("ລຶບ");
        delete_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(catagory_field2)
                    .addComponent(status_combobox, 0, 133, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(update_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(delete_btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catagory_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(status_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(save_btn1)
                    .addComponent(update_btn1)
                    .addComponent(delete_btn1))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout catagory_panelLayout = new javax.swing.GroupLayout(catagory_panel);
        catagory_panel.setLayout(catagory_panelLayout);
        catagory_panelLayout.setHorizontalGroup(
            catagory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addGroup(catagory_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
            .addGroup(catagory_panelLayout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(370, 370, 370))
        );
        catagory_panelLayout.setVerticalGroup(
            catagory_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(catagory_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
        );

        show_panel.add(catagory_panel, "card3");

        POS_panel.setBackground(new java.awt.Color(255, 255, 255));

        pos_table.setBackground(new java.awt.Color(255, 255, 255));
        pos_table.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        pos_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ລະຫັດ", "ບາໂຄດ", "ຊື່ສິນຄ້າ", "ລາຄາ", "ຈຳນວນ", "ລວມ"
            }
        ));
        pos_table.setGridColor(new java.awt.Color(255, 255, 255));
        pos_table.setRowHeight(20);
        pos_table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pos_tableKeyReleased(evt);
            }
        });
        jScrollPane4.setViewportView(pos_table);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        barcode_field2.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N
        barcode_field2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barcode_field2KeyPressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel10.setText("ລະຫັດບາໂຄດ:");

        add_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        add_btn.setText("ເພີ່ມ");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        pay_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        pay_btn.setText("ຈ່າຍເງິນ");
        pay_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btnActionPerformed(evt);
            }
        });

        deletePOS_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        deletePOS_btn.setText("ລຶບ");
        deletePOS_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePOS_btnActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel12.setText("ຊື່ສິນຄ້າ:");

        jLabel13.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel13.setText("ລາຄາລວມ:");

        total_field2.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        total_field2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        product_field2.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        quantity_field2.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        price_field2.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        receive_field2.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        receive_field2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel14.setText("ຈຳນວນ:");

        jLabel15.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel15.setText("ເງິນຮັບມາ:");

        jLabel17.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel17.setText("້ເງິນທ້ອນ");

        jLabel19.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel19.setText("ລາຄາ:");

        change_field2.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        change_field2.setForeground(new java.awt.Color(204, 0, 0));
        change_field2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clear_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        clear_btn.setText("ລ້່າງ");
        clear_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(add_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(deletePOS_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(clear_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(barcode_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(price_field2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quantity_field2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel17)
                                                .addGap(28, 28, 28)
                                                .addComponent(change_field2))
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(receive_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(product_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(483, 483, 483)
                                .addComponent(total_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barcode_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(receive_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(change_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(product_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(price_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)))))
                    .addComponent(total_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity_field2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn)
                    .addComponent(deletePOS_btn)
                    .addComponent(pay_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout POS_panelLayout = new javax.swing.GroupLayout(POS_panel);
        POS_panel.setLayout(POS_panelLayout);
        POS_panelLayout.setHorizontalGroup(
            POS_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, POS_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        POS_panelLayout.setVerticalGroup(
            POS_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POS_panelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        show_panel.add(POS_panel, "card4");

        bill_panel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("ໃບບີນສີນຄ້າ");

        order_bill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ເລກໃບບິນ", "date", "ລຳດັບ", "ລະຫັດສິນຄ້າ", "ຈຳນວນ", "ລາຄາ"
            }
        ));
        jScrollPane1.setViewportView(order_bill);

        deletebill_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        deletebill_btn.setText("ລຶບ");
        deletebill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebill_btnActionPerformed(evt);
            }
        });

        refreshbill_btn.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        refreshbill_btn.setText("Refresh");
        refreshbill_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbill_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bill_panelLayout = new javax.swing.GroupLayout(bill_panel);
        bill_panel.setLayout(bill_panelLayout);
        bill_panelLayout.setHorizontalGroup(
            bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panelLayout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                .addGap(371, 371, 371))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bill_panelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(refreshbill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletebill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        bill_panelLayout.setVerticalGroup(
            bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(bill_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletebill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refreshbill_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86))
        );

        show_panel.add(bill_panel, "card6");

        about_panel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("          ຈຸດປະສົງໃຈການສ້າງໂປຣແກຣມເພື່ອເປັນກໍລະນິສຶກສາ, ພວກເຮົາບໍ່ມີຈຸດປະສົງສະແຫວງຫາຜົນກຳໄຫລ່ແຕ່ຢ່າງໃດ");

        jLabel9.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ກ່ຽວກັບ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 862, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(362, 362, 362)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(340, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout about_panelLayout = new javax.swing.GroupLayout(about_panel);
        about_panel.setLayout(about_panelLayout);
        about_panelLayout.setHorizontalGroup(
            about_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, about_panelLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        about_panelLayout.setVerticalGroup(
            about_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        show_panel.add(about_panel, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseClicked
        product_panel.setVisible(true);
        catagory_panel.setVisible(false);
        POS_panel.setVisible(false);
        about_panel.setVisible(false);
        bill_panel.setVisible(false);
        
        product_IDU_process use =new product_IDU_process();
        use.show_combo(Modelcombox);
    }//GEN-LAST:event_product_labelMouseClicked

    private void product_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseEntered
        product_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box.png")));
        product_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_product_labelMouseEntered

    private void product_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseExited
        product_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box (1).png")));
        product_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_product_labelMouseExited

    private void catagory_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_labelMouseClicked
        product_panel.setVisible(false);
        catagory_panel.setVisible(true);
        POS_panel.setVisible(false);
        about_panel.setVisible(false);
        bill_panel.setVisible(false);
    }//GEN-LAST:event_catagory_labelMouseClicked

    private void catagory_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_labelMouseEntered
        catagory_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miscellaneous.png")));
        catagory_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_catagory_labelMouseEntered

    private void catagory_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_labelMouseExited
        catagory_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miscellaneous (1).png")));
        catagory_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_catagory_labelMouseExited

    private void POS_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseClicked
        product_panel.setVisible(false);
        catagory_panel.setVisible(false);
        POS_panel.setVisible(true);
        about_panel.setVisible(false);
        bill_panel.setVisible(false);
    }//GEN-LAST:event_POS_labelMouseClicked

    private void POS_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseEntered
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag.png")));
        POS_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_POS_labelMouseEntered

    private void POS_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseExited
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag (1).png")));
        POS_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_POS_labelMouseExited

    private void about_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseClicked
        product_panel.setVisible(false);
        catagory_panel.setVisible(false);
        POS_panel.setVisible(false);
        about_panel.setVisible(true);
        bill_panel.setVisible(false);
    }//GEN-LAST:event_about_labelMouseClicked

    private void about_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseEntered
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help.png")));
        about_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_about_labelMouseEntered

    private void about_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseExited
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png")));
        about_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_about_labelMouseExited

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        new loginpos1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exit_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png")));
        exit_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png")));
        exit_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_exit_labelMouseExited
    /*insert data into tb_product product menu*/
    private void save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btnActionPerformed
        String barcode = barcode_field.getText();
        String product = product_field.getText();
        String price = price_field.getText();
        String balance = balance_field.getText();
        String catagory = catagory_combo.getSelectedItem().toString();
        
        if(barcode.equals("") || product.equals("") || catagory.equals("") ||price.equals("") || balance.equals("")){
             JOptionPane.showMessageDialog(this, "You have a blank field");
         }else{
              product_IDU_process use =new product_IDU_process();
              int idCata=use.combox_select(catagory);
              
              use.insert_product(barcode,product,price,balance,idCata);             
              use.show_data(Modelproduct);
              
              barcode_field.setText("");
              product_field.setText("");
              price_field.setText("");
              balance_field.setText("");
              catagory_combo.setSelectedItem("");
        }
    }//GEN-LAST:event_save_btnActionPerformed

    private void bill_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_labelMouseClicked
        product_panel.setVisible(false);
        catagory_panel.setVisible(false);
        POS_panel.setVisible(false);
        about_panel.setVisible(false);
        bill_panel.setVisible(true);
        
    }//GEN-LAST:event_bill_labelMouseClicked

    private void bill_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_labelMouseEntered
        bill_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png")));
        bill_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_bill_labelMouseEntered

    private void bill_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_labelMouseExited
        bill_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill (1).png")));
        bill_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bill_labelMouseExited
    
    /*barcode enter event in menu pos*/
    private void barcode_field2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcode_field2KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                String sql="select * from tb_product where barcode=?";
                PreparedStatement ps= C.prepareStatement(sql);
                ps.setString(1,barcode_field2.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                   rs.getString("product_name");
                   rs.getString("price");
                   
                   product_field2.setText(rs.getString("product_name").trim());
                   price_field2.setText(rs.getString("price").trim());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        
        }
    }//GEN-LAST:event_barcode_field2KeyPressed
     
    /*add button in menu pos*/
    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        int sum=0;
        String barcode=barcode_field2.getText();
        String price=price_field2.getText();
        String quantity=quantity_field2.getText();
        String product=product_field2.getText();
        
        if(barcode.equals("") || product.equals("") || price.equals("") || quantity.equals("")){
             JOptionPane.showMessageDialog(this, "You have a blank field");
        }
        else{
             pos_process pos_obj=new pos_process();

                 for(int k=0;k<pos_table.getRowCount();k++){
                 if(barcode.equals(pos_table.getValueAt(k, 1))){
                     ModelPOS.removeRow(k);
                    
                }
               }
             
             ModelPOS.addRow((Object[]) pos_obj.pos_showdata(barcode,product,price,quantity));
             
            /*summation of all product in jtable*/
            for(int i=0;i<pos_table.getRowCount();i++){
                sum=sum+Integer.parseInt(pos_table.getValueAt(i, 5).toString());
            }
            total_field2.setText(Integer.toString(sum)); 

            barcode_field2.setText("");
            product_field2.setText("");
            price_field2.setText("");
            quantity_field2.setText("");
        }    
    }//GEN-LAST:event_add_btnActionPerformed
    
    /*delete button in menu pos*/
    private void deletePOS_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePOS_btnActionPerformed
        int row=pos_table.getSelectedRow();
        
        if(row==-1){
             JOptionPane.showMessageDialog(this, "You haven't chosen row");
        }else{
            ModelPOS.removeRow(row);
            int sum=0;
            /*summation of all product in jtable*/        
            for(int i=0;i<pos_table.getRowCount();i++){
                sum=sum+Integer.parseInt(pos_table.getValueAt(i, 5).toString());
            }
          total_field2.setText(Integer.toString(sum)); 
        }
        
    }//GEN-LAST:event_deletePOS_btnActionPerformed

    /*pay button in menu pos*/
    private void pay_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btnActionPerformed

            int receive=Integer.parseInt(receive_field2.getText());
            int total=Integer.parseInt(total_field2.getText());
        
            if(receive<total){
                JOptionPane.showMessageDialog(this, "Your money isn't enough");
            }
            else{        
                
                pos_process pos=new pos_process();
                int balance=receive-total;
                change_field2.setText(Integer.toString(balance));
                pos.print( total_field2.getText(),receive_field2.getText(),change_field2.getText(),pos_table.getModel());
                pos.sales(pos_table.getModel());
                
                while(0<pos_table.getRowCount()){
                     ModelPOS.removeRow(0);
                     System.out.println("all row="+pos_table.getRowCount());
                    
                }
                
                  
        }
        
    }//GEN-LAST:event_pay_btnActionPerformed
    
    /*show data in table product and table catagory*/
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

           product_IDU_process pro=new product_IDU_process();
            pro.show_data(Modelproduct);
            pro.show_combo(Modelcombox);
            
    
            catagory_IDU_process cata=new catagory_IDU_process();
            cata.show_data(ModelCatagory);
            
            order_process order=new order_process();
            order.show_data(ModelOrder);
         

                  
    }//GEN-LAST:event_formWindowOpened
    
    /*update button in menu product*/
    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        String barcode=barcode_field.getText();
        String product=product_field.getText();
        String catagory= catagory_combo.getSelectedItem().toString();
        String price =  price_field.getText();
        String balance = balance_field.getText();
        
         if(barcode.equals("") || product.equals("") || catagory.equals("") ||price.equals("") || balance.equals("")){
             JOptionPane.showMessageDialog(this, "You have a blank field");
         }else{
             product_IDU_process use = new product_IDU_process();
             int idCata=use.combox_select(catagory);
             System.out.println("idcata2="+idCata);
             use.edit(barcode,product,idCata,price,balance,product_table.getModel(),product_table.getSelectedRow());
             use.show_data(Modelproduct);
             barcode_field.setText("");
             product_field.setText("");
             catagory_combo.setSelectedItem("");
             price_field.setText("");
             balance_field.setText("");
             this.formWindowOpened(null);
         }
        
    }//GEN-LAST:event_update_btnActionPerformed
    
    /*delete button in menu product*/
    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
       int index=product_table.getSelectedRow();
       if(index==-1){
           JOptionPane.showMessageDialog(this, "You haven't chosen row");
       }else{
           product_IDU_process use = new product_IDU_process();
           use.delete(product_table.getModel(),index);
           use.show_data(Modelproduct);
           this.formWindowOpened(null);
       } 
    }//GEN-LAST:event_delete_btnActionPerformed
    
    /*mouse click event for update in menu product*/
    private void product_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_tableMouseClicked
        try {
            barcode_field.setText(product_table.getValueAt(product_table.getSelectedRow(),1).toString());
            product_field.setText(product_table.getValueAt(product_table.getSelectedRow(),2).toString());
            price_field.setText(product_table.getValueAt(product_table.getSelectedRow(),3).toString());
            balance_field.setText(product_table.getValueAt(product_table.getSelectedRow(),4).toString());
            catagory_combo.setSelectedItem(product_table.getValueAt(product_table.getSelectedRow(),5).toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_product_tableMouseClicked

    private void clear_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btnActionPerformed
       barcode_field2.setText("");
       product_field2.setText("");
       catagory_field2.setText("");
       price_field2.setText("");
       quantity_field2.setText("");
       total_field2.setText("");
       receive_field2.setText("");
       change_field2.setText("");
    }//GEN-LAST:event_clear_btnActionPerformed

    private void deletebill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebill_btnActionPerformed
        int index=order_bill.getSelectedRow();
        
        order_process order=new order_process();
        order.delete_order(order_bill.getModel(),index);
        order.show_data(ModelOrder);
    }//GEN-LAST:event_deletebill_btnActionPerformed
    
    /*insert value into tb_catagory menu catagory*/
    private void save_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_btn1ActionPerformed
        try {
            String catagory_name=catagory_field2.getText();       
            String status_catagory=status_combobox.getSelectedItem().toString();
            
        if(catagory_name.equals("")){
              JOptionPane.showMessageDialog(this, "You have a blank field");
        }else{
               catagory_IDU_process cata=new catagory_IDU_process();
               cata.insert_catagory(catagory_name, status_catagory);
               cata.show_data(ModelCatagory);
               catagory_field2.setText("");
               status_combobox.setSelectedItem("ຍັງເຫລືອ");
           }
         
        } catch (Exception e) {
            e.printStackTrace();
          }
        
    }//GEN-LAST:event_save_btn1ActionPerformed
    /*update tb_catagory menu catgory*/
    private void update_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btn1ActionPerformed
        String name=catagory_field2.getText();
        String status=status_combobox.getSelectedItem().toString();
        int index=catagory_table.getSelectedRow();
        
        if(index==-1){
            JOptionPane.showMessageDialog(this, "You haven't chosen row");
        }else{
            catagory_IDU_process cata=new catagory_IDU_process();
            cata.update_catagory(name, status,catagory_table.getModel(),index);
            cata.show_data(ModelCatagory);
            catagory_field2.setText("");
            status_combobox.setSelectedItem("ຍັງເຫລືອ");
        }  
    }//GEN-LAST:event_update_btn1ActionPerformed
    /*delete tb_catagory menu catagory*/
    private void delete_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btn1ActionPerformed
        int index=catagory_table.getSelectedRow();
        if(index==-1){
            JOptionPane.showMessageDialog(this, "You haven't chosen row");
        }else{
            catagory_IDU_process cata=new catagory_IDU_process();
            cata.delete_catagory(catagory_table.getModel(),index);
            cata.show_data(ModelCatagory);
        }   
    }//GEN-LAST:event_delete_btn1ActionPerformed
    /*muose click catagory table menu*/
    private void catagory_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_tableMouseClicked
        try {
        catagory_field2.setText(catagory_table.getValueAt(catagory_table.getSelectedRow(),1).toString());
        int status=Integer.parseInt(catagory_table.getValueAt(catagory_table.getSelectedRow(), 2).toString());
            if(status==1){
                status_combobox.setSelectedItem("ຍັງເຫລືອ");
            }else{
                status_combobox.setSelectedItem("ບໍ່ເຫລືອ");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_catagory_tableMouseClicked
    /*clear btn product menu*/
    private void clear_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn2ActionPerformed
       barcode_field.setText("");
       product_field.setText("");
       catagory_combo.setSelectedItem("");
       price_field.setText("");
       balance_field.setText("");
    }//GEN-LAST:event_clear_btn2ActionPerformed

    private void refreshbill_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbill_btnActionPerformed
        order_process order=new order_process();
        order.show_data(ModelOrder);
    }//GEN-LAST:event_refreshbill_btnActionPerformed

    private void pos_tableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pos_tableKeyReleased
           if(evt.getKeyCode()==KeyEvent.VK_ENTER){
                    int row=pos_table.getSelectedRow();
                
                if(row==-1){
                     JOptionPane.showMessageDialog(this, "You haven't chosen row");
                }else{
                    ModelPOS.removeRow(row);
                    int sum=0;
                    /*summation of all product in jtable*/        
                    for(int i=0;i<pos_table.getRowCount();i++){
                        sum=sum+Integer.parseInt(pos_table.getValueAt(i, 5).toString());
                    }
                  total_field2.setText(Integer.toString(sum)); 
                }
        }
    }//GEN-LAST:event_pos_tableKeyReleased
      
   
                                                                                             
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 new loginpos1().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel POS_label;
    private javax.swing.JPanel POS_panel;
    private javax.swing.JLabel about_label;
    private javax.swing.JPanel about_panel;
    private javax.swing.JButton add_btn;
    private javax.swing.JTextField balance_field;
    private javax.swing.JTextField barcode_field;
    private javax.swing.JTextField barcode_field2;
    private javax.swing.JLabel bill_label;
    private javax.swing.JPanel bill_panel;
    private javax.swing.JComboBox<String> catagory_combo;
    private javax.swing.JTextField catagory_field2;
    private javax.swing.JLabel catagory_label;
    private javax.swing.JPanel catagory_panel;
    private javax.swing.JTable catagory_table;
    private javax.swing.JTextField change_field2;
    private javax.swing.JButton clear_btn;
    private javax.swing.JButton clear_btn2;
    private javax.swing.JButton deletePOS_btn;
    private javax.swing.JButton delete_btn;
    private javax.swing.JButton delete_btn1;
    private javax.swing.JButton deletebill_btn;
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel icon_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JTable order_bill;
    private javax.swing.JButton pay_btn;
    private javax.swing.JTable pos_table;
    private javax.swing.JTextField price_field;
    private javax.swing.JTextField price_field2;
    private javax.swing.JTextField product_field;
    private javax.swing.JTextField product_field2;
    private javax.swing.JLabel product_label;
    private javax.swing.JPanel product_panel;
    private javax.swing.JTable product_table;
    private javax.swing.JTextField quantity_field2;
    private javax.swing.JTextField receive_field2;
    private javax.swing.JButton refreshbill_btn;
    private javax.swing.JButton save_btn;
    private javax.swing.JButton save_btn1;
    private javax.swing.JPanel show_panel;
    private javax.swing.JComboBox<String> status_combobox;
    private javax.swing.JPanel top_panel;
    private javax.swing.JTextField total_field2;
    private javax.swing.JButton update_btn;
    private javax.swing.JButton update_btn1;
    // End of variables declaration//GEN-END:variables
}
