/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPOS;

import DbConn.DbConn;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IT-Laotelecom
 */
public class mainpos2 extends javax.swing.JFrame {
    Connection C = DbConn.getConn();
    DefaultTableModel ModelPOS5;
    DefaultTableModel ModelOrder5;

    /**
     * Creates new form mainpos2
     */
    public mainpos2() {
        initComponents();
         pos_table5.getTableHeader().setFont(new Font("Phetsarath OT",Font.PLAIN,14){});
         order_bill2.getTableHeader().setFont(new Font("Phetsarath OT",Font.PLAIN,14){});
         ModelOrder5=(DefaultTableModel)order_bill2.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        icon_label = new javax.swing.JLabel();
        POS_label = new javax.swing.JLabel();
        bill_label = new javax.swing.JLabel();
        about_label = new javax.swing.JLabel();
        exit_label = new javax.swing.JLabel();
        top_panel = new javax.swing.JPanel();
        show_panel2 = new javax.swing.JPanel();
        POS_panel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pos_table5 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        barcode_field5 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        add_btn3 = new javax.swing.JButton();
        pay_btn3 = new javax.swing.JButton();
        deletePOS_btn3 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        total_field5 = new javax.swing.JTextField();
        product_field5 = new javax.swing.JTextField();
        quantity_field5 = new javax.swing.JTextField();
        price_field5 = new javax.swing.JTextField();
        receive_field5 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        change_field5 = new javax.swing.JTextField();
        clear_btn3 = new javax.swing.JButton();
        bill_panel2 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        order_bill2 = new javax.swing.JTable();
        refreshbill_btn5 = new javax.swing.JButton();
        about_panel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel39 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(955, 520));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        menu_panel.setBackground(new java.awt.Color(244, 244, 244));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        icon_label.setForeground(new java.awt.Color(0, 102, 204));
        icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_label.setText("SM-POS");
        menu_panel.add(icon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 76));

        POS_label.setBackground(new java.awt.Color(255, 255, 255));
        POS_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        POS_label.setForeground(new java.awt.Color(51, 51, 51));
        POS_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag (1).png"))); // NOI18N
        POS_label.setText("       ຂາຍສິນຄ້າ");
        POS_label.setOpaque(true);
        POS_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                POS_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                POS_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                POS_labelMouseExited(evt);
            }
        });
        menu_panel.add(POS_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        bill_label.setBackground(new java.awt.Color(255, 255, 255));
        bill_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        bill_label.setForeground(new java.awt.Color(51, 51, 51));
        bill_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bill_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill (1).png"))); // NOI18N
        bill_label.setText("        ໃບບິນ");
        bill_label.setOpaque(true);
        bill_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bill_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bill_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bill_labelMouseExited(evt);
            }
        });
        menu_panel.add(bill_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));

        about_label.setBackground(new java.awt.Color(255, 255, 255));
        about_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        about_label.setForeground(new java.awt.Color(51, 51, 51));
        about_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png"))); // NOI18N
        about_label.setText("        ກ່ຽວກັບ");
        about_label.setOpaque(true);
        about_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                about_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about_labelMouseExited(evt);
            }
        });
        menu_panel.add(about_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 140, 35));

        exit_label.setBackground(new java.awt.Color(255, 255, 255));
        exit_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        exit_label.setForeground(new java.awt.Color(51, 51, 51));
        exit_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        exit_label.setText("    ອອກຈາກລະບົບ");
        exit_label.setOpaque(true);
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        menu_panel.add(exit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 140, -1));

        top_panel.setBackground(new java.awt.Color(51, 51, 51));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_panel2.setLayout(new java.awt.CardLayout());

        POS_panel2.setBackground(new java.awt.Color(255, 255, 255));

        pos_table5.setBackground(new java.awt.Color(255, 255, 255));
        pos_table5.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        pos_table5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ລະຫັດ", "ບາໂຄດ", "ຊື່ສິນຄ້າ", "ລາຄາ", "ຈຳນວນ", "ລວມ"
            }
        ));
        pos_table5.setGridColor(new java.awt.Color(255, 255, 255));
        pos_table5.setRowHeight(20);
        jScrollPane4.setViewportView(pos_table5);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        barcode_field5.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N
        barcode_field5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                barcode_field5KeyPressed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel31.setText("ລະຫັດບາໂຄດ:");

        add_btn3.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        add_btn3.setText("ເພີ່ມ");
        add_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btn3ActionPerformed(evt);
            }
        });

        pay_btn3.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        pay_btn3.setText("ຈ່າຍເງິນ");
        pay_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pay_btn3ActionPerformed(evt);
            }
        });

        deletePOS_btn3.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        deletePOS_btn3.setText("ລຶບ");
        deletePOS_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePOS_btn3ActionPerformed(evt);
            }
        });

        jLabel32.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel32.setText("ຊື່ສິນຄ້າ:");

        jLabel33.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel33.setText("ລາຄາລວມ:");

        total_field5.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        total_field5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        product_field5.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        quantity_field5.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        price_field5.setFont(new java.awt.Font("Phetsarath OT", 0, 12)); // NOI18N

        receive_field5.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        receive_field5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel34.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel34.setText("ຈຳນວນ:");

        jLabel35.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel35.setText("ເງິນຮັບມາ:");

        jLabel36.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel36.setText("້ເງິນທ້ອນ");

        jLabel37.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        jLabel37.setText("ລາຄາ:");

        change_field5.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        change_field5.setForeground(new java.awt.Color(204, 0, 0));
        change_field5.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        clear_btn3.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        clear_btn3.setText("ລ້່າງ");
        clear_btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clear_btn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(add_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(deletePOS_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(clear_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(214, 214, 214)
                        .addComponent(pay_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(barcode_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(price_field5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(quantity_field5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel36)
                                                .addGap(28, 28, 28)
                                                .addComponent(change_field5))
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)
                                                .addComponent(receive_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(product_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(483, 483, 483)
                                .addComponent(total_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(barcode_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel35)
                            .addComponent(receive_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(change_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel36)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(product_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(price_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel37)))))
                    .addComponent(total_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantity_field5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_btn3)
                    .addComponent(deletePOS_btn3)
                    .addComponent(pay_btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clear_btn3))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout POS_panel2Layout = new javax.swing.GroupLayout(POS_panel2);
        POS_panel2.setLayout(POS_panel2Layout);
        POS_panel2Layout.setHorizontalGroup(
            POS_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        POS_panel2Layout.setVerticalGroup(
            POS_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(POS_panel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        show_panel2.add(POS_panel2, "card2");

        bill_panel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel38.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("ໃບບີນສີນຄ້າ");

        order_bill2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ເລກໃບບິນ", "date", "ລຳດັບ", "ລະຫັດສິນຄ້າ", "ຈຳນວນ", "ລາຄາ"
            }
        ));
        jScrollPane2.setViewportView(order_bill2);

        refreshbill_btn5.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        refreshbill_btn5.setText("Refresh");
        refreshbill_btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbill_btn5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bill_panel2Layout = new javax.swing.GroupLayout(bill_panel2);
        bill_panel2.setLayout(bill_panel2Layout);
        bill_panel2Layout.setHorizontalGroup(
            bill_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panel2Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(371, 371, 371))
            .addComponent(jScrollPane2)
            .addGroup(bill_panel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(refreshbill_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bill_panel2Layout.setVerticalGroup(
            bill_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bill_panel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(refreshbill_btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        show_panel2.add(bill_panel2, "card3");

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel39.setFont(new java.awt.Font("Phetsarath OT", 0, 14)); // NOI18N
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel39.setText("          ຈຸດປະສົງໃຈການສ້າງໂປຣແກຣມເພື່ອເປັນກໍລະນິສຶກສາ, ພວກເຮົາບໍ່ມີຈຸດປະສົງສະແຫວງຫາຜົນກຳໄຫລ່ແຕ່ຢ່າງໃດ");

        jLabel9.setFont(new java.awt.Font("Phetsarath OT", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ກ່ຽວກັບ");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(336, 336, 336))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(346, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout about_panel2Layout = new javax.swing.GroupLayout(about_panel2);
        about_panel2.setLayout(about_panel2Layout);
        about_panel2Layout.setHorizontalGroup(
            about_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, about_panel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        about_panel2Layout.setVerticalGroup(
            about_panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        show_panel2.add(about_panel2, "card4");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(show_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(show_panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void POS_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseClicked
        bill_panel2.setVisible(false);
        about_panel2.setVisible(false);
        POS_panel2.setVisible(true);
    }//GEN-LAST:event_POS_labelMouseClicked

    private void POS_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseEntered
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag.png")));
        POS_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_POS_labelMouseEntered

    private void POS_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseExited
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag (1).png")));
        POS_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_POS_labelMouseExited

    private void bill_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_labelMouseClicked
       
        bill_panel2.setVisible(true);
        about_panel2.setVisible(false);
        POS_panel2.setVisible(false);
        
    }//GEN-LAST:event_bill_labelMouseClicked

    private void bill_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_labelMouseEntered
        bill_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png")));
        bill_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_bill_labelMouseEntered

    private void bill_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bill_labelMouseExited
        bill_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill (1).png")));
        bill_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_bill_labelMouseExited

    private void about_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseClicked

        bill_panel2.setVisible(false);
        about_panel2.setVisible(true);
        POS_panel2.setVisible(false);
    }//GEN-LAST:event_about_labelMouseClicked

    private void about_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseEntered
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help.png")));
        about_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_about_labelMouseEntered

    private void about_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseExited
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png")));
        about_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_about_labelMouseExited

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        new loginpos1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exit_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png")));
        exit_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png")));
        exit_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_exit_labelMouseExited

    private void barcode_field5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barcode_field5KeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            try {
                String sql="select * from tb_product where barcode=?";
                PreparedStatement ps= C.prepareStatement(sql);
                ps.setString(1,barcode_field5.getText());
                ResultSet rs=ps.executeQuery();
                while(rs.next()){
                    rs.getString("product_name");
                    rs.getString("price");

                    product_field5.setText(rs.getString("product_name").trim());
                    price_field5.setText(rs.getString("price").trim());
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

        }
    }//GEN-LAST:event_barcode_field5KeyPressed

    private void add_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btn3ActionPerformed
        int sum=0;
        String barcode=barcode_field5.getText();
        String price=price_field5.getText();
        String quantity=quantity_field5.getText();
        String product=product_field5.getText();

        /*put data into adapter(defaultablemodel) then show data on jtable*/
        pos_process pos_obj=new pos_process();
        ModelPOS5 = (DefaultTableModel)pos_table5.getModel();
        ModelPOS5.addRow((Object[]) pos_obj.pos_showdata(barcode,product,price,quantity));

        /*summation of all product in jtable*/
        for(int i=0;i<pos_table5.getRowCount();i++){
            sum=sum+Integer.parseInt(pos_table5.getValueAt(i, 5).toString());
        }
        total_field5.setText(Integer.toString(sum));

        barcode_field5.setText("");
        product_field5.setText("");
        price_field5.setText("");
        quantity_field5.setText("");

    }//GEN-LAST:event_add_btn3ActionPerformed

    private void pay_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pay_btn3ActionPerformed

        int receive=Integer.parseInt(receive_field5.getText());
        int total=Integer.parseInt(total_field5.getText());

        if(receive<total){
            JOptionPane.showMessageDialog(this, "Your money isn't enough");
        }else{

            pos_process pos=new pos_process();
            int balance=receive-total;
            change_field5.setText(Integer.toString(balance));
            pos.print( total_field5.getText(),receive_field5.getText(),change_field5.getText(),pos_table5.getModel());
            pos.sales(pos_table5.getModel());
             while(0<pos_table5.getRowCount()){
                     ModelPOS5.removeRow(0);
                     System.out.println("all row="+pos_table5.getRowCount());
                    
                }

        }

    }//GEN-LAST:event_pay_btn3ActionPerformed

    private void deletePOS_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePOS_btn3ActionPerformed
        ModelPOS5.removeRow(pos_table5.getSelectedRow());
        int sum=0;
        /*summation of all product in jtable*/
        for(int i=0;i<pos_table5.getRowCount();i++){
            sum=sum+Integer.parseInt(pos_table5.getValueAt(i, 5).toString());
        }
        total_field5.setText(Integer.toString(sum));
    }//GEN-LAST:event_deletePOS_btn3ActionPerformed

    private void clear_btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clear_btn3ActionPerformed
        barcode_field5.setText("");
        product_field5.setText("");
        price_field5.setText("");
        total_field5.setText("");
        receive_field5.setText("");
        change_field5.setText("");
    }//GEN-LAST:event_clear_btn3ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
            DefaultTableModel ModelOrder=(DefaultTableModel)order_bill2.getModel();    
            order_process order=new order_process();
            order.show_data(ModelOrder);
    }//GEN-LAST:event_formWindowOpened

    private void refreshbill_btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbill_btn5ActionPerformed
       order_process bill=new order_process();
       bill.show_data(ModelOrder5);
    }//GEN-LAST:event_refreshbill_btn5ActionPerformed

     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpos2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel POS_label;
    private javax.swing.JPanel POS_panel2;
    private javax.swing.JLabel about_label;
    private javax.swing.JPanel about_panel2;
    private javax.swing.JButton add_btn3;
    private javax.swing.JTextField barcode_field5;
    private javax.swing.JLabel bill_label;
    private javax.swing.JPanel bill_panel2;
    private javax.swing.JTextField change_field5;
    private javax.swing.JButton clear_btn3;
    private javax.swing.JButton deletePOS_btn3;
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel icon_label;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JTable order_bill2;
    private javax.swing.JButton pay_btn3;
    private javax.swing.JTable pos_table5;
    private javax.swing.JTextField price_field5;
    private javax.swing.JTextField product_field5;
    private javax.swing.JTextField quantity_field5;
    private javax.swing.JTextField receive_field5;
    private javax.swing.JButton refreshbill_btn5;
    private javax.swing.JPanel show_panel2;
    private javax.swing.JPanel top_panel;
    private javax.swing.JTextField total_field5;
    // End of variables declaration//GEN-END:variables
}
