/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPOS;

/**
 *
 * @author IT-Laotelecom
 */
public class mainpos1 extends javax.swing.JFrame {

    /**
     * Creates new form mainpos1
     */
    public mainpos1() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu_panel = new javax.swing.JPanel();
        icon_label = new javax.swing.JLabel();
        product_label = new javax.swing.JLabel();
        catagory_label = new javax.swing.JLabel();
        POS_label = new javax.swing.JLabel();
        about_label = new javax.swing.JLabel();
        exit_label = new javax.swing.JLabel();
        top_panel = new javax.swing.JPanel();
        show_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        menu_panel.setBackground(new java.awt.Color(244, 244, 244));
        menu_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        icon_label.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        icon_label.setForeground(new java.awt.Color(0, 102, 204));
        icon_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icon_label.setText("SM-POS");
        menu_panel.add(icon_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 76));

        product_label.setBackground(new java.awt.Color(255, 255, 255));
        product_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        product_label.setForeground(new java.awt.Color(0, 0, 0));
        product_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        product_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box (1).png"))); // NOI18N
        product_label.setText("         ສິນຄ້າ");
        product_label.setToolTipText("");
        product_label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        product_label.setOpaque(true);
        product_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                product_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                product_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                product_labelMouseExited(evt);
            }
        });
        menu_panel.add(product_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 104, 148, -1));

        catagory_label.setBackground(new java.awt.Color(255, 255, 255));
        catagory_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        catagory_label.setForeground(new java.awt.Color(51, 51, 51));
        catagory_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        catagory_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miscellaneous (1).png"))); // NOI18N
        catagory_label.setText("      ປະເພດສິນຄ້າ");
        catagory_label.setOpaque(true);
        catagory_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                catagory_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catagory_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catagory_labelMouseExited(evt);
            }
        });
        menu_panel.add(catagory_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, 148, -1));

        POS_label.setBackground(new java.awt.Color(255, 255, 255));
        POS_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        POS_label.setForeground(new java.awt.Color(51, 51, 51));
        POS_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag (1).png"))); // NOI18N
        POS_label.setText("       ຂາຍສິນຄ້າ");
        POS_label.setOpaque(true);
        POS_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                POS_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                POS_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                POS_labelMouseExited(evt);
            }
        });
        menu_panel.add(POS_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 244, 148, -1));

        about_label.setBackground(new java.awt.Color(255, 255, 255));
        about_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        about_label.setForeground(new java.awt.Color(51, 51, 51));
        about_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png"))); // NOI18N
        about_label.setText("        ກ່ຽວກັບ");
        about_label.setOpaque(true);
        about_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                about_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                about_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                about_labelMouseExited(evt);
            }
        });
        menu_panel.add(about_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 306, 148, 35));

        exit_label.setBackground(new java.awt.Color(255, 255, 255));
        exit_label.setFont(new java.awt.Font("Phetsarath OT", 1, 12)); // NOI18N
        exit_label.setForeground(new java.awt.Color(51, 51, 51));
        exit_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png"))); // NOI18N
        exit_label.setText("          ອອກ");
        exit_label.setOpaque(true);
        exit_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_labelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exit_labelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exit_labelMouseExited(evt);
            }
        });
        menu_panel.add(exit_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 367, 148, -1));

        top_panel.setBackground(new java.awt.Color(51, 51, 51));
        top_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        show_panel.setBackground(new java.awt.Color(255, 255, 255));
        show_panel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(top_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                    .addComponent(show_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void product_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_product_labelMouseClicked

    private void product_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseEntered
        product_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box.png")));
        product_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_product_labelMouseEntered

    private void product_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_product_labelMouseExited
        product_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/box (1).png")));
        product_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_product_labelMouseExited

    private void catagory_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_catagory_labelMouseClicked

    private void catagory_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_labelMouseEntered
        catagory_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miscellaneous.png")));
        catagory_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_catagory_labelMouseEntered

    private void catagory_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catagory_labelMouseExited
        catagory_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/miscellaneous (1).png")));
        catagory_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_catagory_labelMouseExited

    private void POS_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_POS_labelMouseClicked

    private void POS_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseEntered
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag.png")));
        POS_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_POS_labelMouseEntered

    private void POS_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_POS_labelMouseExited
        POS_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shopping-bag (1).png")));
        POS_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_POS_labelMouseExited

    private void about_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_about_labelMouseClicked

    private void about_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseEntered
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help.png")));
        about_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_about_labelMouseEntered

    private void about_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_about_labelMouseExited
        about_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/help (1).png")));
        about_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_about_labelMouseExited

    private void exit_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_labelMouseClicked

    private void exit_labelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseEntered
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout (1).png")));
        exit_label.setBackground(new java.awt.Color(204,204,204));
    }//GEN-LAST:event_exit_labelMouseEntered

    private void exit_labelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_labelMouseExited
        exit_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout.png")));
        exit_label.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_exit_labelMouseExited
             
    
                                                                          
    
                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainpos1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainpos1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel POS_label;
    private javax.swing.JLabel about_label;
    private javax.swing.JLabel catagory_label;
    private javax.swing.JLabel exit_label;
    private javax.swing.JLabel icon_label;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menu_panel;
    private javax.swing.JLabel product_label;
    private javax.swing.JPanel show_panel;
    private javax.swing.JPanel top_panel;
    // End of variables declaration//GEN-END:variables
}
